### ISSUE TITLE
pipstrap pip version doesn't support manylinux1 wheels

### ISSUE THREAD

**Issue by bmw** [erikrose/pipstrap#12]
Looks like support for this was added in [pip 8.1.0](https://github.com/pypa/pip/blob/master/NEWS.rst#810-2016-03-05) with wider support being added in [pip 8.1.2](https://github.com/pypa/pip/blob/master/NEWS.rst#812-2016-05-10).

Can we upgrade the version of `pip` used here so we can use manylinux1 wheels in `certbot-auto`? This affects the `cffi` and `cryptography` packages and is a big win for us as no compilation will no longer be required.

I'm happy to create a PR. Do you have a preference for the version of `pip` we use? If there are no new dependencies, any reason not to use the newest version?

**Comment by alex** [comment]
I think it was an accident that this was closed?

**Comment by bmw** [comment]
Thanks @alex! Using the phrase "resolve erikrose/pipstrap#12"  in certbot/certbot#4972 caused this. Reopening.

**Comment by erikrose** [comment]
Newest would be great! But beware that the reason I chose the versions I chose was that they had simple dependency relationships. I didn't record history very well on this point, but I do see a suspicious comment…

    # This version of setuptools has only optional dependencies:

…which makes me suspect it was a setuptools thing (though I don't see anything overtly wrong with the current version of setuptools). See if you can find another, newer selection of packages which can be installed everywhere unconditionally.

**Comment by alex** [comment]
There were a handful of releases where setuptools had deps, and then it went back to not having deps again.
